// -------------------------------------------------------------
// 
// File Name: hdlsrc2\FFTscheme2\FirthStage_16.v
// Created: 2020-11-01 20:23:00
// 
// Generated by MATLAB 9.4 and HDL Coder 3.12
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FirthStage_16
// Source Path: FFTscheme2/FFTv2/Butterflies/128 input 5 step  /FirthStage 16
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FirthStage_16
          (In1,
           In2,
           Const_input_re,
           Const_input_im,
           Out1_re,
           Out1_im,
           Out2_re,
           Out2_im);


  input   signed [10:0] In1;  // sfix11_En3
  input   signed [10:0] In2;  // sfix11_En3
  input   signed [10:0] Const_input_re;  // sfix11_En9
  input   signed [10:0] Const_input_im;  // sfix11_En9
  output  signed [11:0] Out1_re;  // sfix12_En3
  output  signed [11:0] Out1_im;  // sfix12_En3
  output  signed [11:0] Out2_re;  // sfix12_En3
  output  signed [11:0] Out2_im;  // sfix12_En3


  wire signed [21:0] Product_mul_temp;  // sfix22_En12
  wire signed [11:0] Product_cast;  // sfix12_En4
  wire signed [12:0] Product_cast_1;  // sfix13_En4
  wire signed [21:0] Product_mul_temp_1;  // sfix22_En12
  wire signed [11:0] Product_add_cast;  // sfix12_En4
  wire signed [12:0] Product_add_cast_1;  // sfix13_En4
  wire signed [12:0] Product_add_temp;  // sfix13_En4
  wire signed [11:0] Product_out1_re;  // sfix12_En4
  wire signed [11:0] Product_out1_im;  // sfix12_En4
  wire signed [12:0] Sum_add_cast;  // sfix13_En4
  wire signed [12:0] Sum_add_cast_1;  // sfix13_En4
  wire signed [12:0] Sum_add_temp;  // sfix13_En4
  wire signed [12:0] Sum_cast;  // sfix13_En4
  wire signed [11:0] Sum_out1_re;  // sfix12_En3
  wire signed [11:0] Sum_out1_im;  // sfix12_En3
  wire signed [12:0] Sum1_sub_cast;  // sfix13_En4
  wire signed [12:0] Sum1_sub_cast_1;  // sfix13_En4
  wire signed [12:0] Sum1_sub_temp;  // sfix13_En4
  wire signed [12:0] Sum1_cast;  // sfix13_En4
  wire signed [12:0] Sum1_cast_1;  // sfix13_En4
  wire signed [11:0] Sum1_out1_re;  // sfix12_En3
  wire signed [11:0] Sum1_out1_im;  // sfix12_En3


  assign Product_mul_temp = Const_input_re * In2;
  assign Product_cast = ((Product_mul_temp[21] == 1'b0) && (Product_mul_temp[20:19] != 2'b00) ? 12'sb011111111111 :
              ((Product_mul_temp[21] == 1'b1) && (Product_mul_temp[20:19] != 2'b11) ? 12'sb100000000000 :
              $signed(Product_mul_temp[19:8])));
  assign Product_cast_1 = {Product_cast[11], Product_cast};
  assign Product_out1_re = ((Product_cast_1[12] == 1'b0) && (Product_cast_1[11] != 1'b0) ? 12'sb011111111111 :
              ((Product_cast_1[12] == 1'b1) && (Product_cast_1[11] != 1'b1) ? 12'sb100000000000 :
              $signed(Product_cast_1[11:0])));
  assign Product_mul_temp_1 = Const_input_im * In2;
  assign Product_add_cast = ((Product_mul_temp_1[21] == 1'b0) && (Product_mul_temp_1[20:19] != 2'b00) ? 12'sb011111111111 :
              ((Product_mul_temp_1[21] == 1'b1) && (Product_mul_temp_1[20:19] != 2'b11) ? 12'sb100000000000 :
              $signed(Product_mul_temp_1[19:8])));
  assign Product_add_cast_1 = {Product_add_cast[11], Product_add_cast};
  assign Product_add_temp = Product_add_cast_1 + 13'sb0000000000000;
  assign Product_out1_im = ((Product_add_temp[12] == 1'b0) && (Product_add_temp[11] != 1'b0) ? 12'sb011111111111 :
              ((Product_add_temp[12] == 1'b1) && (Product_add_temp[11] != 1'b1) ? 12'sb100000000000 :
              $signed(Product_add_temp[11:0])));



  assign Sum_add_cast = {In1[10], {In1, 1'b0}};
  assign Sum_add_cast_1 = {Product_out1_re[11], Product_out1_re};
  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_1;
  assign Sum_out1_re = Sum_add_temp[12:1];
  assign Sum_cast = {Product_out1_im[11], Product_out1_im};
  assign Sum_out1_im = Sum_cast[12:1];



  assign Out1_re = Sum_out1_re;

  assign Out1_im = Sum_out1_im;

  assign Sum1_sub_cast = {In1[10], {In1, 1'b0}};
  assign Sum1_sub_cast_1 = {Product_out1_re[11], Product_out1_re};
  assign Sum1_sub_temp = Sum1_sub_cast - Sum1_sub_cast_1;
  assign Sum1_out1_re = Sum1_sub_temp[12:1] + $signed({1'b0, Sum1_sub_temp[0]});
  assign Sum1_cast = {Product_out1_im[11], Product_out1_im};
  assign Sum1_cast_1 =  - (Sum1_cast);
  assign Sum1_out1_im = Sum1_cast_1[12:1] + $signed({1'b0, Sum1_cast_1[0]});



  assign Out2_re = Sum1_out1_re;

  assign Out2_im = Sum1_out1_im;

endmodule  // FirthStage_16

