// -------------------------------------------------------------
// 
// File Name: hdlsrc2\FFTscheme2\ThirdStageB_18.v
// Created: 2020-11-01 20:22:58
// 
// Generated by MATLAB 9.4 and HDL Coder 3.12
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ThirdStageB_18
// Source Path: FFTscheme2/FFTv2/Butterflies/128 input 3 step /ThirdStageB 18
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ThirdStageB_18
          (In1,
           In2,
           Const_input,
           Out1,
           Out2);


  input   signed [10:0] In1;  // sfix11_En4
  input   signed [10:0] In2;  // sfix11_En4
  input   signed [1:0] Const_input;  // sfix2
  output  signed [10:0] Out1;  // sfix11_En3
  output  signed [10:0] Out2;  // sfix11_En3


  wire signed [12:0] Product_mul_temp;  // sfix13_En4
  wire signed [10:0] Product_out1;  // sfix11_En4
  wire signed [11:0] Sum_add_cast;  // sfix12_En4
  wire signed [11:0] Sum_add_cast_1;  // sfix12_En4
  wire signed [11:0] Sum_add_temp;  // sfix12_En4
  wire signed [10:0] Sum_out1;  // sfix11_En3
  wire signed [11:0] Sum1_sub_cast;  // sfix12_En4
  wire signed [11:0] Sum1_sub_cast_1;  // sfix12_En4
  wire signed [11:0] Sum1_sub_temp;  // sfix12_En4
  wire signed [10:0] Sum1_out1;  // sfix11_En3


  assign Product_mul_temp = Const_input * In2;
  assign Product_out1 = Product_mul_temp[10:0];



  assign Sum_add_cast = {In1[10], In1};
  assign Sum_add_cast_1 = {Product_out1[10], Product_out1};
  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_1;
  assign Sum_out1 = Sum_add_temp[11:1] + $signed({1'b0, Sum_add_temp[0]});



  assign Out1 = Sum_out1;

  assign Sum1_sub_cast = {In1[10], In1};
  assign Sum1_sub_cast_1 = {Product_out1[10], Product_out1};
  assign Sum1_sub_temp = Sum1_sub_cast - Sum1_sub_cast_1;
  assign Sum1_out1 = Sum1_sub_temp[11:1];



  assign Out2 = Sum1_out1;

endmodule  // ThirdStageB_18

